data_full <- read.csv("./household_power_consumption.txt",header=T, sep=';', na.strings="?", nrows=2075259, check.names=F, stringsAsFactors=F, comment.char="", quote='\"')
data_full$Date <- as.Date(data_full$Date, format="%d/%m/%Y")
data <- subset(data_full, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(data_full)
datetime <- paste(as.Date(data$Date), data$Time)
data$Datetime <- strptime(datetime, format="%Y-%m-%d %H:%M:%S", tz = "GMT")
with(data, plot(Datetime, Sub_metering_1, type = "n"))
with(data, { plot(Datetime, Sub_metering_1, type="l", ylab="Global Active Power (kilowatts)", xlab="")
             lines(Datetime, Sub_metering_2, col='Red')
             lines(Datetime, Sub_metering_3,col='Blue')
             })
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png", height=480, width=480)
dev.off()